services:
  - type: web
    name: unishare
    env: python
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn unishare.unishare.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: unishare.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: unishare-db
          property: connectionString
databases:
  - name: unishare-db
    plan: free
