# Generated by Django 5.2.3 on 2025-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
