# Generated by Django 5.2.3 on 2026-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_downloads_count_resource_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
