# Generated by Django 5.2.3 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
