# Generated by Django 5.2.3 on 2026-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_provider_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploader_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
