# Generated by Django 5.2.3 on 2026-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resource_uploader_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_base64',
            field=models.TextField(blank=True, help_text='Stores the raw file data as Base64 to bypass Cloudinary restrictions', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
